language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq subversion
script: py.test
sudo: required