language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
before_install:
  - sudo sh -c 'echo "deb http://opensource.wandisco.com/ubuntu `lsb_release -cs` svn19" >> /etc/apt/sources.list.d/subversion19.list'
  - sudo wget -q http://opensource.wandisco.com/wandisco-debian.gpg -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get remove subversion
  - sudo apt-get install -qq subversion
script: python setup.py test
sudo: required